u luminauser - "Lumina Linux Live" /home/luminauser /bin/bash
m luminauser wheel
m luminauser video
m luminauser audio
m luminauser input
m luminauser storage
m luminauser network
m luminauser autologin
