# airootfs/etc/calamares/modules/fstab.conf
---
mountOptions:
    default: defaults,noatime
    ext4: defaults,noatime
    btrfs: defaults,noatime,space_cache=v2,compress=zstd,discard=async
    xfs: defaults,noatime

# Opciones para particiones EFI/Boot
efiMountOptions: umask=0077
