---
backend: pacman
skip_if_no_internet: false
update_db: true
update_system: false

operations:
  - install:
    - base
    - linux
    - linux-firmware
    - mkinitcpio
    - grub
    - efibootmgr
    - os-prober
