---
efiSystemPartition:     "/boot/efi"
userSwapChoices:        [none, small, suspend, file]
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice:      none
defaultFileSystemType:  "btrfs"

btrfsSubvolumes:
    - mountPoint: /
      subvolume: /@
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /var/cache
      subvolume: /@cache
    - mountPoint: /var/log
      subvolume: /@log
    # Para el uso de Snapper
    - mountPoint: /.snapshots
      subvolume: /@snapshots
