---
# Activar servicios críticos en el sistema recién instalado
units:
  # La red (Vital para que tengas internet al reiniciar)
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  # El gestor de inicio de sesión gráfico (Para que levante tu KDE Plasma)
  - name: "sddm.service"
    action: "enable"
    mandatory: true
  # El demonio de Bluetooth (Para que funcionen tus códecs LDAC y aptX)
  - name: "bluetooth.service"
    action: "enable"
    mandatory: false
  # Sincronización de hora por red (Siempre útil)
  - name: "systemd-timesyncd.service"
    action: "enable"
    mandatory: true
  # ¡Nuestro flamante limpiador de SSDs en segundo plano!
  - name: "fstrim.timer"
    action: "enable"
    mandatory: true
  # Servicio de configuracion de Snapper (solo corre una vez y se desactiva)
  - name: "lumina-postinstall"
    action: "enable"
