---
dontChroot: false
timeout: 999
script:
    - "rm -f /var/lib/pacman/db.lck"
    - "rm -rf /etc/pacman.d/gnupg"
    - "rm -f /etc/resolv.conf"
    - "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
    - "pacman-key --init"
    - "pacman-key --populate archlinux"
    - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
    - "rm -f /etc/mkinitcpio.d/linux.preset"
    - "pacman -Sy --noconfirm linux"
