---
dontChroot: false
timeout: 999
script:
    # --- Integración NVIDIA ---
    - |
      if lspci | grep -i vga | grep -i nvidia > /dev/null; then
          if ! grep -q "nvidia-drm.modeset=1" /etc/default/grub; then
              sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="nvidia-drm.modeset=1 /' /etc/default/grub
          fi
          grub-mkconfig -o /boot/grub/grub.cfg
          cat <<EOF >> /etc/environment
      GBM_BACKEND=nvidia-drm
      __GLX_VENDOR_LIBRARY_NAME=nvidia
      WLR_NO_HARDWARE_CURSORS=1
      MOZ_ENABLE_WAYLAND=1
      EOF
      fi

    # --- Limpieza y Post-instalación ---
    - "sed -i '/luminauser ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers"
    - "rm -f /etc/sudoers.d/10-installer"
    - "rm -f /etc/sddm.conf.d/autologin.conf"
    - "pacman -R --noconfirm calamares || true"
    - "pacman -R --noconfirm falkon || true"
    - "rm -f /usr/share/applications/instalar-lumina.desktop"
    - "rm -f /home/*/Desktop/instalar-lumina.desktop"
    - "rm -f /etc/skel/Desktop/instalar-lumina.desktop"
    - "pacman -U --noconfirm /usr/share/lumina/yay-bin-*.pkg.tar.zst"
    - "pacman -U --noconfirm /usr/share/lumina/libpamac-aur-*.pkg.tar.zst /usr/share/lumina/pamac-aur-*.pkg.tar.zst"
    - "rm -f /usr/share/lumina/*.pkg.tar.zst"
    - "rm -f /etc/xdg/autostart/calamares.desktop"
    - "rm -rf /etc/calamares"
    - "rm -rf /var/log/calamares"
    # --- Exterminar fantasmas del Archiso e inicializar Keyring ---
    # 1. Borramos los archivos existentes para evitar conflictos
    - "rm -f /etc/systemd/system/pacman-init.service"
    - "rm -f /etc/systemd/system/etc-pacman.d-gnupg.mount"

    # 2. Ahora sí enmascaramos (aquí es donde systemctl crea el enlace a /dev/null)
    - "systemctl mask pacman-init.service"
    - "systemctl mask etc-pacman.d-gnupg.mount"

    # 3. Limpieza y preparación del Keyring
    - "rm -rf /etc/pacman.d/gnupg"
    - "mkdir -p /etc/pacman.d/gnupg"
    - "chmod 700 /etc/pacman.d/gnupg"
    - "pacman-key --init"
    - "pacman-key --populate archlinux lumina"
    - "pacman-key --lsign-key 093B74E82FCA45014329D8B1FE2080D27FBE66D8"
