---
dontChroot: false
timeout: 999
script:
    - "rm -rf /etc/pacman.d/gnupg"
    - "pacman-key --init"
    - "pacman-key --populate archlinux"
    - "pacman-key --populate lumina"
    - "pacman-key --lsign-key 093B74E82FCA45014329D8B1FE2080D27FBE66D8"
