---
defaultGroups:
    - wheel
    - video
    - audio
    - storage
    - optical
    - network
    - lp
    - scanner
    - input
    - users
autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true
