---
modules-search: [ local ]

instances:
  - module:       shellprocess
    id:           init_stage
    config:       shellprocess_init.conf
  - module:       shellprocess
    id:           cleanup_stage
    config:       shellprocess_cleanup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - netinstall
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - locale
  - keyboard
  - localecfg
  - fstab
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@init_stage
  - packages
  - initcpio
  - grubcfg
  - bootloader
  - removeuser
  - shellprocess@cleanup_stage
  - umount
- show:
  - finished

branding: lumina
liveSessionUser: "luminauser"
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
